### ISSUE TITLE
May you provide the pretrain model on UCF101 dataset?

### ISSUE THREAD

**Issue by LYKlyk** [okankop/Efficient-3DCNNs#8]
Thank you for publish source code! I try to train MobileNet_0.5x on UCF101 dataset, but i can not arrive the precision of 62.17 on top 1. I just can arrive the precision of 40% on top 1, so what should i do when i train this model? I have already use the pretrain model which is trained on Kinetics-600.

**Comment by okankop** [comment]
Most probably you are getting confused about clip and video accuracy. When you train the models, you see the clip accuracy. After the training is done, you should first run the models with '--test' mode in order to create 'val.json', and then, you need to run 'video_accuracy.py' in utils folder to calculate video accuracies.

I have put it to de README :) I hope this solves your problem.

**Comment by okankop** [comment]
I believe the issue is resolved.

**Comment by slighting666** [comment]
I want to verify the ability of transfer learning,where can i get the pretrain model which is trained on Kinetics-600？thanks！ @LYKlyk @okankop
